In [87]:
import pandas as pd
import keras
import tensorflow as tf
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
%matplotlib inline
#loading the dataset
df=pd.read_csv('loan_data.csv')

In [46]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [47]:
#shape of data
df.shape

(614, 13)

In [48]:
#finding missing values in the dataset
df.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [49]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [50]:
#data types
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [51]:

df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

df['Married'].fillna(df['Married'].mode()[0], inplace=True)

df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)

df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)

df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0], inplace=True)

df['Credit_History'].fillna(df['Credit_History'].mode()[0], inplace=True)

In [52]:
df['LoanAmount'].fillna(df['LoanAmount'].mean(), inplace=True)

In [53]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [54]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y

In [55]:
#converting the categories into numbers
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})
df['Married'] = df['Married'].map({'No': 0, 'Yes': 1})
df['Dependents'] = df['Dependents'].map({'0': 0, '1': 1, '2': 2, '3+': 3})
df['Education'] = df['Education'].map({'Graduate': 1, 'Not Graduate': 0})
df['Self_Employed'] = df['Self_Employed'].map({'No': 0, 'Yes': 1})
df['Property_Area'] = df['Property_Area'].map({'Rural': 0, 'Semiurban': 1, 'Urban': 2})
df['Loan_Status'] = df['Loan_Status'].map({'N': 0, 'Y': 1})

In [56]:
#we bring all the variable value in range 0 to 1


for i in df.columns[1:]:
    df[i] = (df[i] - df[i].min()) / (df[i].max() - df[i].min())

In [57]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [59]:
df = df.drop('Loan_ID', axis=1)
df.shape

(614, 12)

In [63]:


# Independent variables (features)
X = df.iloc[:, :-1]  # Selecting all columns except the last one

# Dependent variable (target)
y = df.iloc[:, -1]   # Selecting the last column

print(X.shape)
print(y.shape)

(614, 11)
(614,)

In [64]:

X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=df['Loan_Status'],random_state=10,test_size=0.2)

In [66]:
#import sequential model
from keras.models import Sequential
#importing different layers
from keras.layers import InputLayer, Dense

In [72]:
X_train.shape
#number of input feature
input_neurons= X_train.shape[1]
#output will be either yes or no that is either 1 or 0
output_neuron= 1

In [80]:
#number of hidden layers
num_of_hidden_layers=2
neuron_hidden_layer1= 15
neuron_hidden_layer2= 10

In [81]:
#activation function
model=Sequential()
model.add(InputLayer(input_shape=(input_neurons)))
model.add(Dense(units=neuron_hidden_layer1, activation='tanh'))
model.add(Dense(units=neuron_hidden_layer2, activation='tanh'))
model.add(Dense(units=output_neuron, activation='sigmoid'))

In [75]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 60

 dense_1 (Dense)             (None, 10)                60

 dense_2 (Dense)             (None, 1)                 11

=================================================================
Total params: 131 (524.00 Byte)
Trainable params: 131 (524.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [82]:
#number of parameters
input_neurons*neuron_hidden_layer1

165

In [83]:
#adding bias
input_neurons*neuron_hidden_layer1+10

175

In [84]:
#for hidden layer 2
neuron_hidden_layer1*neuron_hidden_layer2

150

In [85]:
#adding bias
neuron_hidden_layer1*neuron_hidden_layer2 + 10

160

In [86]:
neuron_hidden_layer2*output_neuron + 1

11

In [88]:
#compiling the model

model.compile(loss='binary_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [91]:

model_history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50)

Epoch 1/50
16/16 [==============================] - 2s 18ms/step - loss: 0.6612 - accuracy: 0.6558 - val_loss: 0.6497 - val_accuracy: 0.6585
Epoch 2/50
16/16 [==============================] - 0s 6ms/step - loss: 0.6428 - accuracy: 0.6721 - val_loss: 0.6341 - val_accuracy: 0.6911
Epoch 3/50
16/16 [==============================] - 0s 6ms/step - loss: 0.6297 - accuracy: 0.6802 - val_loss: 0.6224 - val_accuracy: 0.6911
Epoch 4/50
16/16 [==============================] - 0s 6ms/step - loss: 0.6200 - accuracy: 0.6884 - val_loss: 0.6150 - val_accuracy: 0.6911
Epoch 5/50
16/16 [==============================] - 0s 5ms/step - loss: 0.6138 - accuracy: 0.6864 - val_loss: 0.6094 - val_accuracy: 0.6911
Epoch 6/50
16/16 [==============================] - 0s 6ms/step - loss: 0.6089 - accuracy: 0.6864 - val_loss: 0.6054 - val_accuracy: 0.6911
Epoch 7/50
16/16 [==============================] - 0s 5ms/step - loss: 0.6057 - accuracy: 0.6864 - val_loss: 0.6023 - val_accuracy: 0.6911
Epoch 8/50
16/16 [==============================] - 0s 6ms/step - loss: 0.6029 - accuracy: 0.6864 - val_loss: 0.6001 - val_accuracy: 0.6911
Epoch 9/50
16/16 [==============================] - 0s 6ms/step - loss: 0.6010 - accuracy: 0.6864 - val_loss: 0.5987 - val_accuracy: 0.6911
Epoch 10/50
16/16 [==============================] - 0s 6ms/step - loss: 0.5995 - accuracy: 0.6864 - val_loss: 0.5972 - val_accuracy: 0.6911
Epoch 11/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5981 - accuracy: 0.6864 - val_loss: 0.5958 - val_accuracy: 0.6911
Epoch 12/50
16/16 [==============================] - 0s 6ms/step - loss: 0.5968 - accuracy: 0.6864 - val_loss: 0.5945 - val_accuracy: 0.6911
Epoch 13/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5956 - accuracy: 0.6864 - val_loss: 0.5935 - val_accuracy: 0.6911
Epoch 14/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5946 - accuracy: 0.6864 - val_loss: 0.5924 - val_accuracy: 0.6911
Epoch 15/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5935 - accuracy: 0.6864 - val_loss: 0.5913 - val_accuracy: 0.6911
Epoch 16/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5924 - accuracy: 0.6864 - val_loss: 0.5902 - val_accuracy: 0.6911
Epoch 17/50
16/16 [==============================] - 0s 6ms/step - loss: 0.5913 - accuracy: 0.6864 - val_loss: 0.5892 - val_accuracy: 0.6911
Epoch 18/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5903 - accuracy: 0.6864 - val_loss: 0.5882 - val_accuracy: 0.6911
Epoch 19/50
16/16 [==============================] - 0s 6ms/step - loss: 0.5892 - accuracy: 0.6864 - val_loss: 0.5872 - val_accuracy: 0.6911
Epoch 20/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5881 - accuracy: 0.6864 - val_loss: 0.5861 - val_accuracy: 0.6911
Epoch 21/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5870 - accuracy: 0.6864 - val_loss: 0.5851 - val_accuracy: 0.6911
Epoch 22/50
16/16 [==============================] - 0s 6ms/step - loss: 0.5860 - accuracy: 0.6884 - val_loss: 0.5840 - val_accuracy: 0.6911
Epoch 23/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5848 - accuracy: 0.6884 - val_loss: 0.5829 - val_accuracy: 0.6911
Epoch 24/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5836 - accuracy: 0.6884 - val_loss: 0.5817 - val_accuracy: 0.6911
Epoch 25/50
16/16 [==============================] - 0s 6ms/step - loss: 0.5825 - accuracy: 0.6884 - val_loss: 0.5806 - val_accuracy: 0.6911
Epoch 26/50
16/16 [==============================] - 0s 6ms/step - loss: 0.5812 - accuracy: 0.6884 - val_loss: 0.5794 - val_accuracy: 0.6911
Epoch 27/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5800 - accuracy: 0.6884 - val_loss: 0.5784 - val_accuracy: 0.6911
Epoch 28/50
16/16 [==============================] - 0s 8ms/step - loss: 0.5789 - accuracy: 0.6884 - val_loss: 0.5772 - val_accuracy: 0.6911
Epoch 29/50
16/16 [==============================] - 0s 8ms/step - loss: 0.5777 - accuracy: 0.6884 - val_loss: 0.5760 - val_accuracy: 0.6911
Epoch 30/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5765 - accuracy: 0.6884 - val_loss: 0.5748 - val_accuracy: 0.6911
Epoch 31/50
16/16 [==============================] - 0s 8ms/step - loss: 0.5752 - accuracy: 0.6884 - val_loss: 0.5736 - val_accuracy: 0.6911
Epoch 32/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5739 - accuracy: 0.6884 - val_loss: 0.5723 - val_accuracy: 0.6911
Epoch 33/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5726 - accuracy: 0.6884 - val_loss: 0.5711 - val_accuracy: 0.6911
Epoch 34/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5713 - accuracy: 0.6884 - val_loss: 0.5697 - val_accuracy: 0.6911
Epoch 35/50
16/16 [==============================] - 0s 8ms/step - loss: 0.5699 - accuracy: 0.6884 - val_loss: 0.5684 - val_accuracy: 0.6911
Epoch 36/50
16/16 [==============================] - 0s 8ms/step - loss: 0.5685 - accuracy: 0.6925 - val_loss: 0.5671 - val_accuracy: 0.6911
Epoch 37/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5672 - accuracy: 0.6925 - val_loss: 0.5655 - val_accuracy: 0.6911
Epoch 38/50
16/16 [==============================] - 0s 8ms/step - loss: 0.5655 - accuracy: 0.6904 - val_loss: 0.5642 - val_accuracy: 0.6911
Epoch 39/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5643 - accuracy: 0.6945 - val_loss: 0.5628 - val_accuracy: 0.6992
Epoch 40/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5630 - accuracy: 0.7006 - val_loss: 0.5614 - val_accuracy: 0.6992
Epoch 41/50
16/16 [==============================] - 0s 7ms/step - loss: 0.5614 - accuracy: 0.7067 - val_loss: 0.5600 - val_accuracy: 0.6992
Epoch 42/50
16/16 [==============================] - 0s 8ms/step - loss: 0.5599 - accuracy: 0.7108 - val_loss: 0.5585 - val_accuracy: 0.6992
Epoch 43/50
16/16 [==============================] - 0s 9ms/step - loss: 0.5585 - accuracy: 0.7169 - val_loss: 0.5570 - val_accuracy: 0.6992
Epoch 44/50
16/16 [==============================] - 0s 8ms/step - loss: 0.5569 - accuracy: 0.7189 - val_loss: 0.5556 - val_accuracy: 0.6992
Epoch 45/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5554 - accuracy: 0.7189 - val_loss: 0.5542 - val_accuracy: 0.7073
Epoch 46/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5538 - accuracy: 0.7251 - val_loss: 0.5527 - val_accuracy: 0.7154
Epoch 47/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5523 - accuracy: 0.7291 - val_loss: 0.5511 - val_accuracy: 0.7154
Epoch 48/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5509 - accuracy: 0.7332 - val_loss: 0.5496 - val_accuracy: 0.7154
Epoch 49/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5492 - accuracy: 0.7413 - val_loss: 0.5480 - val_accuracy: 0.7317
Epoch 50/50
16/16 [==============================] - 0s 5ms/step - loss: 0.5475 - accuracy: 0.7434 - val_loss: 0.5464 - val_accuracy: 0.7317

In [94]:
#predictions
predicted_status = model.predict(X_test)

4/4 [==============================] - 0s 3ms/step

In [97]:
#accuracy
accuracyscore=(y_test, predicted_status)
print(accuracyscore)

(507    0.0
493    1.0
434    1.0
125    1.0
294    1.0
      ...
82     0.0
295    1.0
369    0.0
450    0.0
363    1.0
Name: Loan_Status, Length: 123, dtype: float64, array([[0.7432985 ],
       [0.63879734],
       [0.7431603 ],
       [0.6792108 ],
       [0.73942584],
       [0.7124452 ],
       [0.7604564 ],
       [0.7171363 ],
       [0.77777725],
       [0.6548096 ],
       [0.73718107],
       [0.64676946],
       [0.7201898 ],
       [0.7814551 ],
       [0.7061414 ],
       [0.70913476],
       [0.6869038 ],
       [0.76278794],
       [0.70329297],
       [0.6728981 ],
       [0.7149548 ],
       [0.7634923 ],
       [0.7352049 ],
       [0.7597712 ],
       [0.7357885 ],
       [0.78766197],
       [0.7003694 ],
       [0.6527732 ],
       [0.7717611 ],
       [0.7338222 ],
       [0.75814277],
       [0.76838976],
       [0.7600164 ],
       [0.47951782],
       [0.60891855],
       [0.50599736],
       [0.67946374],
       [0.74274063],
       [0.7009278 ],
       [0.7904284 ],
       [0.7487605 ],
       [0.64481574],
       [0.7248279 ],
       [0.774323  ],
       [0.5982655 ],
       [0.76944757],
       [0.74230945],
       [0.7120121 ],
       [0.7520306 ],
       [0.5706087 ],
       [0.7283773 ],
       [0.74216545],
       [0.73708725],
       [0.7609923 ],
       [0.74369466],
       [0.5346932 ],
       [0.7668139 ],
       [0.71470726],
       [0.4723562 ],
       [0.68389696],
       [0.71593845],
       [0.6904919 ],
       [0.70956767],
       [0.73300385],
       [0.74486905],
       [0.73621273],
       [0.7645067 ],
       [0.5782797 ],
       [0.7480171 ],
       [0.69779056],
       [0.5595443 ],
       [0.73309666],
       [0.74458   ],
       [0.676929  ],
       [0.75712955],
       [0.7174253 ],
       [0.72857344],
       [0.6672812 ],
       [0.66635907],
       [0.49376133],
       [0.7439046 ],
       [0.75009406],
       [0.75167805],
       [0.6616855 ],
       [0.6671099 ],
       [0.50727767],
       [0.7489488 ],
       [0.78153473],
       [0.76249695],
       [0.7467171 ],
       [0.7650923 ],
       [0.74161655],
       [0.69197243],
       [0.58719254],
       [0.7700629 ],
       [0.7724314 ],
       [0.7706546 ],
       [0.5027322 ],
       [0.7375248 ],
       [0.68780404],
       [0.70157623],
       [0.73042077],
       [0.7461556 ],
       [0.7161548 ],
       [0.7412917 ],
       [0.6557245 ],
       [0.76221615],
       [0.70937663],
       [0.76661026],
       [0.74440557],
       [0.5756105 ],
       [0.73950297],
       [0.72505367],
       [0.44182193],
       [0.50755066],
       [0.741669  ],
       [0.7898248 ],
       [0.76115197],
       [0.7714912 ],
       [0.7886156 ],
       [0.6903608 ],
       [0.49228296],
       [0.76761955]], dtype=float32))